### PR TITLE
Bug/1510 required logos

### PR DESCRIPTION
**Pull request by jacobkellas**
[AB#1510](https://dev.azure.com/dsd-sdsd/ad8a8cd2-ef49-4e7c-bae2-6f8729a38334/_workitems/edit/1510)

Before:
image

After:
image

### CODE REVIEW

**Review by sdsd-dsd — CHANGES_REQUESTED** [review]
Looks way better! I think we decided to keep the required button and make it x-small though. Let's try that first!

**Comment by jacobkellas** [comment]
image

Something like this or should we continue to spell out the statute and make it x-small as well?

**Comment by jacobkellas** [comment]
The text for the statute looks pretty bad x-small, I would suggest keeping it with just the scales icon.

**Comment by sdsd-dsd** [comment]
I like the way you had just the scale icon at the end of the header. Maybe use a red warning triangle symbol at the beginning of the header. Goal is to reduce everything to a single line, wherever possible.

**Review by sdsd-dsd — APPROVED** [review]

**Pull request merged**
